site_name: Lora Book
site_url: https://arduitronics.github.io/lora-book/
nav:
    - Home: index.md
    - Content: content.md
    - GK00001: gk00001.md
    - Barebone ESP8266: barebone.md
    - License: license.md
    - About: about.md
theme:
    name: material

# Extensions
markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.keys
  - codehilite:
      linenums: true

extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'